"""
models/quiz.py — QuizSession, QuizQuestion, QuizAnswer models.

QuizSession: Tracks one adaptive assessment attempt for a learner.
QuizQuestion: A seeded or AI-generated question in the question bank.
QuizAnswer: Records a learner's selected answer within a session.
"""

import enum
import uuid
from datetime import datetime, timezone

from ..extensions import db


class QuizStatus(enum.Enum):
    """Possible lifecycle states of a quiz session."""
    in_progress = "in_progress"
    completed   = "completed"
    abandoned   = "abandoned"


class QuestionSource(enum.Enum):
    """Whether a question was pre-seeded by developers or generated by the LLM."""
    seeded = "seeded"
    ai     = "ai"


class QuizSession(db.Model):
    """
    One adaptive assessment session for a single learner and goal.

    current_difficulty tracks the adaptive engine's current question level (1–5).
    score is NULL until the session completes.
    """

    __tablename__ = "quiz_sessions"

    __table_args__ = (
        db.Index("idx_quiz_sessions_user_id", "user_id"),
        db.Index("idx_quiz_sessions_goal_id", "goal_id"),
        db.Index("idx_quiz_sessions_status",  "status"),
    )

    id = db.Column(db.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    goal_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("goals.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    status = db.Column(
        db.Enum(QuizStatus),
        nullable=False,
        default=QuizStatus.in_progress,
    )
    # How many questions have been answered so far in this session
    current_question_number = db.Column(db.SmallInteger, nullable=False, default=0)
    # Current adaptive difficulty level (1=beginner … 5=expert)
    current_difficulty = db.Column(
        db.SmallInteger,
        nullable=False,
        default=3,
    )
    # Final weighted skill score 0–100; set on completion
    score = db.Column(db.Numeric(5, 2), nullable=True)
    total_questions = db.Column(db.SmallInteger, nullable=False, default=0)
    started_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    completed_at = db.Column(db.DateTime(timezone=True), nullable=True)

    # ── Relationships ────────────────────────────────────────────────────
    user = db.relationship("User", back_populates="quiz_sessions")
    goal = db.relationship("Goal", back_populates="quiz_sessions")
    answers = db.relationship(
        "QuizAnswer", back_populates="session", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return (
            f"<QuizSession id={self.id} status={self.status.value} "
            f"difficulty={self.current_difficulty}>"
        )


class QuizQuestion(db.Model):
    """
    A multiple-choice question in the question bank for a specific goal.

    options is a JSONB array of exactly 4 answer strings.
    correct_option_index is 0-based.
    difficulty ranges from 1 (easiest) to 5 (hardest).
    """

    __tablename__ = "quiz_questions"

    __table_args__ = (
        db.Index("idx_quiz_questions_goal_diff", "goal_id", "difficulty"),
        db.Index("idx_quiz_questions_source",    "source"),
    )

    id = db.Column(db.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    goal_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("goals.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    question_text = db.Column(db.Text, nullable=False)
    # Stored as JSON array: ["Option A", "Option B", "Option C", "Option D"]
    options = db.Column(db.JSON, nullable=False)
    # 0-indexed position of the correct option within `options`
    correct_option_index = db.Column(db.SmallInteger, nullable=False)
    difficulty = db.Column(db.SmallInteger, nullable=False)
    source = db.Column(
        db.Enum(QuestionSource),
        nullable=False,
        default=QuestionSource.seeded,
    )
    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ────────────────────────────────────────────────────
    goal = db.relationship("Goal", back_populates="quiz_questions")
    answers = db.relationship("QuizAnswer", back_populates="question")

    def __repr__(self):
        return (
            f"<QuizQuestion id={self.id} difficulty={self.difficulty} "
            f"source={self.source.value}>"
        )


class QuizAnswer(db.Model):
    """
    Records one learner answer within a quiz session.
    Links the session, the question answered, and the chosen option.
    """

    __tablename__ = "quiz_answers"

    __table_args__ = (
        db.Index("idx_quiz_answers_session_id",  "session_id"),
        db.Index("idx_quiz_answers_question_id", "question_id"),
    )

    id = db.Column(db.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("quiz_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    question_id = db.Column(
        db.UUID(as_uuid=True),
        db.ForeignKey("quiz_questions.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    # 0-indexed option the learner selected
    selected_option = db.Column(db.SmallInteger, nullable=False)
    is_correct = db.Column(db.Boolean, nullable=False)
    answered_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ────────────────────────────────────────────────────
    session  = db.relationship("QuizSession",  back_populates="answers")
    question = db.relationship("QuizQuestion", back_populates="answers")

    def __repr__(self):
        return (
            f"<QuizAnswer session={self.session_id} question={self.question_id} "
            f"correct={self.is_correct}>"
        )
