"""initial schema

Revision ID: ea4b5a12d305
Revises: 
Create Date: 2026-06-11 22:03:20.573909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4b5a12d305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('generated_content', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cv_entity', 'content_versions', ['entity_type', 'entity_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_name'), 'goals', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('idx_token_blocklist_created', 'token_blocklist', ['created_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('instructor', sa.String(length=200), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_goal_id', 'courses', ['goal_id'], unique=False)
    op.create_index('idx_courses_title', 'courses', ['title'], unique=False)
    op.create_index(op.f('ix_courses_goal_id'), 'courses', ['goal_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'ai', name='questionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_questions_goal_diff', 'quiz_questions', ['goal_id', 'difficulty'], unique=False)
    op.create_index('idx_quiz_questions_source', 'quiz_questions', ['source'], unique=False)
    op.create_index(op.f('ix_quiz_questions_goal_id'), 'quiz_questions', ['goal_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('skill_level', sa.SmallInteger(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_goal_id', 'users', ['goal_id'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_last_active', 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_goal_id'), 'users', ['goal_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('certificate_code', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_code')
    )
    op.create_index('idx_certificates_code', 'certificates', ['certificate_code'], unique=True)
    op.create_index('idx_certificates_course_id', 'certificates', ['course_id'], unique=False)
    op.create_index('idx_certificates_user_id', 'certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_paths_user_goal', 'learning_paths', ['user_id', 'goal_id'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=True),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position', name='uq_module_course_position')
    )
    op.create_index('idx_modules_course_id', 'modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='quizstatus'), nullable=False),
    sa.Column('current_question_number', sa.SmallInteger(), nullable=False),
    sa.Column('current_difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_questions', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_sessions_goal_id', 'quiz_sessions', ['goal_id'], unique=False)
    op.create_index('idx_quiz_sessions_status', 'quiz_sessions', ['status'], unique=False)
    op.create_index('idx_quiz_sessions_user_id', 'quiz_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_goal_id'), 'quiz_sessions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('user_courses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_index('idx_user_courses_completed', 'user_courses', ['completed_at'], unique=False)
    op.create_index('idx_user_courses_course_id', 'user_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_courses_course_id'), 'user_courses', ['course_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_skill_gain', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'position', name='uq_lpi_path_position')
    )
    op.create_index('idx_lpi_course_id', 'learning_path_items', ['course_id'], unique=False)
    op.create_index('idx_lpi_path_id', 'learning_path_items', ['path_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_course_id'), 'learning_path_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_path_id'), 'learning_path_items', ['path_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.SmallInteger(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_answers_question_id', 'quiz_answers', ['question_id'], unique=False)
    op.create_index('idx_quiz_answers_session_id', 'quiz_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_session_id'), 'quiz_answers', ['session_id'], unique=False)
    op.create_table('user_module_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'module_id')
    )
    op.create_index('idx_ump_module_id', 'user_module_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_user_module_progress_module_id'), 'user_module_progress', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_module_progress_module_id'), table_name='user_module_progress')
    op.drop_index('idx_ump_module_id', table_name='user_module_progress')
    op.drop_table('user_module_progress')
    op.drop_index(op.f('ix_quiz_answers_session_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index('idx_quiz_answers_session_id', table_name='quiz_answers')
    op.drop_index('idx_quiz_answers_question_id', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_learning_path_items_path_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_course_id'), table_name='learning_path_items')
    op.drop_index('idx_lpi_path_id', table_name='learning_path_items')
    op.drop_index('idx_lpi_course_id', table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_courses_course_id'), table_name='user_courses')
    op.drop_index('idx_user_courses_course_id', table_name='user_courses')
    op.drop_index('idx_user_courses_completed', table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_goal_id'), table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_user_id', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_status', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_goal_id', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_index('idx_modules_course_id', table_name='modules')
    op.drop_table('modules')
    op.drop_index('idx_learning_paths_user_goal', table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_index('idx_certificates_user_id', table_name='certificates')
    op.drop_index('idx_certificates_course_id', table_name='certificates')
    op.drop_index('idx_certificates_code', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_goal_id'), table_name='users')
    op.drop_index('idx_users_last_active', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_goal_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quiz_questions_goal_id'), table_name='quiz_questions')
    op.drop_index('idx_quiz_questions_source', table_name='quiz_questions')
    op.drop_index('idx_quiz_questions_goal_diff', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_courses_goal_id'), table_name='courses')
    op.drop_index('idx_courses_title', table_name='courses')
    op.drop_index('idx_courses_goal_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_token_blocklist_created', table_name='token_blocklist')
    op.drop_table('token_blocklist')
    op.drop_table('roles')
    op.drop_index(op.f('ix_goals_name'), table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_cv_entity', table_name='content_versions')
    op.drop_table('content_versions')
    # ### end Alembic commands ###
